// Builds the atlas assets from the brand's ikat fabric photo (assets/brand/atlas-source.webp).
// Nothing is drawn: the photo is mirrored into a 2×2 tile so it repeats without seams
// (ikat motifs are symmetric, so the mirror joins are invisible), plus a thin strip for dividers.
//
//   node scripts/process-atlas.mjs
import sharp from "sharp";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "assets/brand/atlas-source.webp");
const OUT = join(root, "public/atlas");
mkdirSync(OUT, { recursive: true });

const { width: w, height: h } = await sharp(SRC).metadata();
const orig = await sharp(SRC).removeAlpha().toBuffer();
const flopped = await sharp(orig).flop().toBuffer(); // mirrored left↔right
const flipped = await sharp(orig).flip().toBuffer(); // mirrored top↕bottom
const both = await sharp(orig).flip().flop().toBuffer();

// 2×2 seamless tile (pixel size 2w×2h, displayed at w×h CSS px → sharp on retina)
const tile = await sharp({ create: { width: w * 2, height: h * 2, channels: 3, background: "#ffffff" } })
  .composite([
    { input: orig, left: 0, top: 0 },
    { input: flopped, left: w, top: 0 },
    { input: flipped, left: 0, top: h },
    { input: both, left: w, top: h },
  ])
  .png()
  .toBuffer();
// 2× file for high-density screens, 1× for everyone else (CSS image-set picks one)
const tile2x = await sharp(tile).webp({ quality: 72 }).toBuffer();
const tile1x = await sharp(tile).resize(w, h).webp({ quality: 78 }).toBuffer();
writeFileSync(join(OUT, "ikat@2x.webp"), tile2x);
writeFileSync(join(OUT, "ikat.webp"), tile1x);

// divider strip: a horizontal band through a row of motifs, repeated along x
const bandTop = Math.round(h * 0.42);
const bandH = Math.round(h * 0.06);
const strip = await sharp(tile)
  .extract({ left: 0, top: bandTop, width: w * 2, height: bandH })
  .resize({ height: 32 })
  .webp({ quality: 82 })
  .toBuffer();
const stripMeta = await sharp(strip).metadata();
writeFileSync(join(OUT, "ikat-strip.webp"), strip);

// display sizes in CSS px (the files are 2× for high-density screens)
const TILE = { width: w, height: h, stripWidth: Math.round(stripMeta.width / 2), stripHeight: 16 };
mkdirSync(join(root, "src/components/atlas"), { recursive: true });
writeFileSync(
  join(root, "src/components/atlas/tiles.ts"),
  `// generated by scripts/process-atlas.mjs — do not edit\nexport const ATLAS_TILE = ${JSON.stringify(TILE)} as const;\n`,
);
console.log("atlas:", TILE, `tile 1x ${(tile1x.length / 1024).toFixed(0)} KB, 2x ${(tile2x.length / 1024).toFixed(0)} KB, strip ${(strip.length / 1024).toFixed(0)} KB`);
